[workspace]
members = [
    "scheds/rust/scx_pardus",
]
resolver = "2"

[profile.release]
opt-level = 3
debug  = false
lto = true
strip = "symbols"
incremental = true
codegen-units = 1
panic = "abort"



